name       : aircrack-ng
version    : 1.2_rc4
release    : 2
source     :
    - http://download.aircrack-ng.org/aircrack-ng-1.2-rc4.tar.gz : d93ac16aade5b4d37ab8cdf6ce4b855835096ccf83deb65ffdeff6d666eaff36
license    : GPL-2.0
component  : network.util
summary    : Aircrack-ng is a complete suite of tools to assess WiFi network security.
description: |
    Aircrack-ng is a complete suite of tools to assess WiFi network security.
builddeps  :
    - pkgconfig(libnl-3.0)
    - pkgconfig(libpcre)
    - pkgconfig(sqlite3)
    - libpcap-devel
rundeps    :
    - ethtool
setup      : |
    %patch -p1 < $pkgfiles/0001-Use-proper-paths-for-packaging.patch
build      : |
    %make SQLITE=true PCRE=true EXPERIMENTAL=true GCRYPT=true
install    : |
    %make_install SQLITE=true PCRE=true EXPERIMENTAL=true GCRYPT=true
