name       : aircrack-ng
version    : 1.3
release    : 4
source     :
    - https://download.aircrack-ng.org/aircrack-ng-1.3.tar.gz : 8ae08a7c28741f6ace2769267112053366550e7f746477081188ad38410383ca
license    : GPL-2.0-or-later
component  : network.util
summary    : Aircrack-ng is a complete suite of tools to assess WiFi network security.
description: |
    Aircrack-ng is a complete suite of tools to assess WiFi network security.
builddeps  :
    - pkgconfig(libnl-3.0)
    - pkgconfig(libpcre)
    - pkgconfig(sqlite3)
    - ethtool
    - libgcrypt-devel
    - libpcap-devel
rundeps    :
    - ethtool
setup      : |
    %autogen --with-gcrypt --with-experimental=yes --disable-static
build      : |
    %make
install    : |
    %make_install
