name       : aircrack-ng
version    : 1.4
release    : 5
source     :
    - https://download.aircrack-ng.org/aircrack-ng-1.4.tar.gz : 96092a8af7af27cdc1923cd5167dfca4a17e9f5fd866973b7b6eb6d3b479e13b
license    : GPL-2.0-or-later
component  : network.util
summary    : Aircrack-ng is a complete suite of tools to assess WiFi network security.
description: |
    Aircrack-ng is a complete suite of tools to assess WiFi network security.
builddeps  :
    - pkgconfig(libnl-3.0)
    - pkgconfig(libpcre)
    - pkgconfig(sqlite3)
    - ethtool
    - libgcrypt-devel
    - libpcap-devel
rundeps    :
    - ethtool
patterns   :
    - main :
        - /usr/lib64/libaircrack-*-1.3.0.so
setup      : |
    %autogen --with-gcrypt --with-experimental=yes --disable-static
build      : |
    %make
install    : |
    %make_install
