name       : aircrack-ng
version    : 1.5.2
release    : 6
source     :
    - https://github.com/aircrack-ng/aircrack-ng/archive/1.5.2.tar.gz : 7e03f9828495a3a1a781ad79e41805971bf7347c092df852820232bca866a19b
license    : GPL-2.0-or-later
component  : network.util
summary    : Aircrack-ng is a complete suite of tools to assess WiFi network security.
description: |
    Aircrack-ng is a complete suite of tools to assess WiFi network security.
builddeps  :
    - pkgconfig(libnl-3.0)
    - pkgconfig(libpcre)
    - pkgconfig(sqlite3)
    - ethtool
    - libgcrypt-devel
    - libpcap-devel
rundeps    :
    - ethtool
patterns   :
    - main :
        - /usr/lib64/libaircrack-*-1.3.0.so
setup      : |
    %autogen --with-gcrypt --with-experimental=yes --disable-static
build      : |
    %make
install    : |
    %make_install
