name       : aircrack-ng
version    : '1.6'
release    : 11
source     :
    - https://github.com/aircrack-ng/aircrack-ng/archive/1.6.tar.gz : c9e7894ba30f5e45b8a20ec43b4599225ac739a795a5bdb98e3f1bbb854d54f7
homepage   : https://www.aircrack-ng.org/
license    : GPL-2.0-or-later
component  : network.util
summary    : Aircrack-ng is a complete suite of tools to assess WiFi network security.
description: |
    Aircrack-ng is a complete suite of tools to assess WiFi network security.
libsplit   : no
builddeps  :
    - pkgconfig(libgcrypt)
    - pkgconfig(libnl-3.0)
    - pkgconfig(libpcap)
    - pkgconfig(libpcre)
    - pkgconfig(sqlite3)
    - ethtool
rundeps    :
    - ethtool
    - iw
    - pciutils
environment: |
    export CFLAGS="${CFLAGS} -fcommon"
setup      : |
    %autogen --with-gcrypt --with-experimental=yes --disable-static
build      : |
    %make
install    : |
    %make_install
check      : |
    %make check
